Enable use of .cmd files as fnlfmt command on Windows
midouest/vsc-fnlfmt pull request #1
Opened 2024-10-06 20:12 UTC by nils-hensel

Spawn command failed on windows using a fnlfmt.cmd file as formatter.
Fixed by spawning child process in a shell environment.

Also updated dependencies to current versions to fix vulnerabilities.

Tested on Windows 11.

2024-10-06 20:14 UTC, nils-hensel commented
Hello, Robin!

I wanted to try out your vsc extension and ran into some problems on Windows.
This should fix it and I hope it does not cause any problems for non-Windows-users!

2024-10-07 01:20 UTC, midouest requested changes
Thank you for fixing this and upgrading the dependencies! I am away from my PC at the moment so I can't validate this, but the extension still works on my Mac so I'm not too worried about it. There are just a couple issues that need to be resolved before merging:

- [ ] Remove package-lock.json
- [ ] Remove the unsupported `--info-verbosity verbose` webpack argument

2024-10-07 01:20 UTC, midouest commented on package-lock.json
> +{
Please remove this file from the PR and only check in the yarn.lock changes. Thanks!

2024-10-07 01:20 UTC, midouest commented on package.json
> +    "webpack-cli": "^5.1.4"
We need to remove the `--info-verbosity verbose` argument passed to webpack in the package.json `watch` script due to the new webpack version.

2024-10-07 18:26 UTC, nils-hensel commented on package-lock.json
> +{
Should I add this file to .gitignore?

2024-10-07 18:40 UTC, nils-hensel commented on package.json
> +    "webpack-cli": "^5.1.4"
Done

2024-10-07 18:44 UTC, nils-hensel commented on package-lock.json
> +{
Otherwise done

2024-10-07 19:44 UTC, midouest approved these changes
Looks great! Thanks!

2024-10-07 19:44 UTC, merged